// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lider_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LiderManagementClient is the client API for LiderManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LiderManagementClient interface {
	Unirse(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Confirmacion, error)
	Jugar(ctx context.Context, in *Jugada, opts ...grpc.CallOption) (*Estado, error)
	Premio(ctx context.Context, in *VerMonto, opts ...grpc.CallOption) (*Monto, error)
}

type liderManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewLiderManagementClient(cc grpc.ClientConnInterface) LiderManagementClient {
	return &liderManagementClient{cc}
}

func (c *liderManagementClient) Unirse(ctx context.Context, in *Peticion, opts ...grpc.CallOption) (*Confirmacion, error) {
	out := new(Confirmacion)
	err := c.cc.Invoke(ctx, "/lider.LiderManagement/Unirse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liderManagementClient) Jugar(ctx context.Context, in *Jugada, opts ...grpc.CallOption) (*Estado, error) {
	out := new(Estado)
	err := c.cc.Invoke(ctx, "/lider.LiderManagement/Jugar", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *liderManagementClient) Premio(ctx context.Context, in *VerMonto, opts ...grpc.CallOption) (*Monto, error) {
	out := new(Monto)
	err := c.cc.Invoke(ctx, "/lider.LiderManagement/Premio", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiderManagementServer is the server API for LiderManagement service.
// All implementations must embed UnimplementedLiderManagementServer
// for forward compatibility
type LiderManagementServer interface {
	Unirse(context.Context, *Peticion) (*Confirmacion, error)
	Jugar(context.Context, *Jugada) (*Estado, error)
	Premio(context.Context, *VerMonto) (*Monto, error)
	mustEmbedUnimplementedLiderManagementServer()
}

// UnimplementedLiderManagementServer must be embedded to have forward compatible implementations.
type UnimplementedLiderManagementServer struct {
}

func (UnimplementedLiderManagementServer) Unirse(context.Context, *Peticion) (*Confirmacion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unirse not implemented")
}
func (UnimplementedLiderManagementServer) Jugar(context.Context, *Jugada) (*Estado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Jugar not implemented")
}
func (UnimplementedLiderManagementServer) Premio(context.Context, *VerMonto) (*Monto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Premio not implemented")
}
func (UnimplementedLiderManagementServer) mustEmbedUnimplementedLiderManagementServer() {}

// UnsafeLiderManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LiderManagementServer will
// result in compilation errors.
type UnsafeLiderManagementServer interface {
	mustEmbedUnimplementedLiderManagementServer()
}

func RegisterLiderManagementServer(s grpc.ServiceRegistrar, srv LiderManagementServer) {
	s.RegisterService(&LiderManagement_ServiceDesc, srv)
}

func _LiderManagement_Unirse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Peticion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiderManagementServer).Unirse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lider.LiderManagement/Unirse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiderManagementServer).Unirse(ctx, req.(*Peticion))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiderManagement_Jugar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Jugada)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiderManagementServer).Jugar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lider.LiderManagement/Jugar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiderManagementServer).Jugar(ctx, req.(*Jugada))
	}
	return interceptor(ctx, in, info, handler)
}

func _LiderManagement_Premio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerMonto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiderManagementServer).Premio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lider.LiderManagement/Premio",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiderManagementServer).Premio(ctx, req.(*VerMonto))
	}
	return interceptor(ctx, in, info, handler)
}

// LiderManagement_ServiceDesc is the grpc.ServiceDesc for LiderManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LiderManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lider.LiderManagement",
	HandlerType: (*LiderManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unirse",
			Handler:    _LiderManagement_Unirse_Handler,
		},
		{
			MethodName: "Jugar",
			Handler:    _LiderManagement_Jugar_Handler,
		},
		{
			MethodName: "Premio",
			Handler:    _LiderManagement_Premio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lider.proto",
}
