// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: proto/lider.proto

package lider_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Peticion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peticion string `protobuf:"bytes,1,opt,name=peticion,proto3" json:"peticion,omitempty"`
}

func (x *Peticion) Reset() {
	*x = Peticion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Peticion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peticion) ProtoMessage() {}

func (x *Peticion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peticion.ProtoReflect.Descriptor instead.
func (*Peticion) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{0}
}

func (x *Peticion) GetPeticion() string {
	if x != nil {
		return x.Peticion
	}
	return ""
}

type Confirmacion struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Confirmacion string `protobuf:"bytes,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
}

func (x *Confirmacion) Reset() {
	*x = Confirmacion{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Confirmacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmacion) ProtoMessage() {}

func (x *Confirmacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmacion.ProtoReflect.Descriptor instead.
func (*Confirmacion) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{1}
}

func (x *Confirmacion) GetConfirmacion() string {
	if x != nil {
		return x.Confirmacion
	}
	return ""
}

type Jugada struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugada int32 `protobuf:"varint,1,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *Jugada) Reset() {
	*x = Jugada{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jugada) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jugada) ProtoMessage() {}

func (x *Jugada) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jugada.ProtoReflect.Descriptor instead.
func (*Jugada) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{2}
}

func (x *Jugada) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado string `protobuf:"bytes,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{3}
}

func (x *Estado) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type VerMonto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vermonto string `protobuf:"bytes,1,opt,name=vermonto,proto3" json:"vermonto,omitempty"`
}

func (x *VerMonto) Reset() {
	*x = VerMonto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerMonto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerMonto) ProtoMessage() {}

func (x *VerMonto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerMonto.ProtoReflect.Descriptor instead.
func (*VerMonto) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{4}
}

func (x *VerMonto) GetVermonto() string {
	if x != nil {
		return x.Vermonto
	}
	return ""
}

type Monto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Monto int32 `protobuf:"varint,1,opt,name=monto,proto3" json:"monto,omitempty"`
}

func (x *Monto) Reset() {
	*x = Monto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lider_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Monto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Monto) ProtoMessage() {}

func (x *Monto) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lider_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Monto.ProtoReflect.Descriptor instead.
func (*Monto) Descriptor() ([]byte, []int) {
	return file_proto_lider_proto_rawDescGZIP(), []int{5}
}

func (x *Monto) GetMonto() int32 {
	if x != nil {
		return x.Monto
	}
	return 0
}

var File_proto_lider_proto protoreflect.FileDescriptor

var file_proto_lider_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x08, 0x50, 0x65,
	0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x74, 0x69, 0x63, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x65, 0x74, 0x69, 0x63, 0x69,
	0x6f, 0x6e, 0x22, 0x32, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x63, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x61, 0x63, 0x69, 0x6f, 0x6e, 0x22, 0x20, 0x0a, 0x06, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61,
	0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x22, 0x20, 0x0a, 0x06, 0x45, 0x73, 0x74, 0x61,
	0x64, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22, 0x26, 0x0a, 0x08, 0x56, 0x65,
	0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x6d, 0x6f, 0x6e,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x76, 0x65, 0x72, 0x6d, 0x6f, 0x6e,
	0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x05, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6d,
	0x6f, 0x6e, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74,
	0x6f, 0x32, 0x91, 0x01, 0x0a, 0x0f, 0x4c, 0x69, 0x64, 0x65, 0x72, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x12,
	0x0f, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x50, 0x65, 0x74, 0x69, 0x63, 0x69, 0x6f, 0x6e,
	0x1a, 0x13, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x61, 0x63, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x05, 0x4a, 0x75, 0x67, 0x61, 0x72, 0x12, 0x0d,
	0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x1a, 0x0d, 0x2e,
	0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x27, 0x0a, 0x06,
	0x50, 0x72, 0x65, 0x6d, 0x69, 0x6f, 0x12, 0x0f, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x56,
	0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x1a, 0x0c, 0x2e, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2e,
	0x4d, 0x6f, 0x6e, 0x74, 0x6f, 0x42, 0x24, 0x5a, 0x22, 0x6c, 0x61, 0x62, 0x6f, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x69, 0x6f, 0x32, 0x2f, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63,
	0x3b, 0x6c, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_lider_proto_rawDescOnce sync.Once
	file_proto_lider_proto_rawDescData = file_proto_lider_proto_rawDesc
)

func file_proto_lider_proto_rawDescGZIP() []byte {
	file_proto_lider_proto_rawDescOnce.Do(func() {
		file_proto_lider_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lider_proto_rawDescData)
	})
	return file_proto_lider_proto_rawDescData
}

var file_proto_lider_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_lider_proto_goTypes = []interface{}{
	(*Peticion)(nil),     // 0: lider.Peticion
	(*Confirmacion)(nil), // 1: lider.Confirmacion
	(*Jugada)(nil),       // 2: lider.Jugada
	(*Estado)(nil),       // 3: lider.Estado
	(*VerMonto)(nil),     // 4: lider.VerMonto
	(*Monto)(nil),        // 5: lider.Monto
}
var file_proto_lider_proto_depIdxs = []int32{
	0, // 0: lider.LiderManagement.Unirse:input_type -> lider.Peticion
	2, // 1: lider.LiderManagement.Jugar:input_type -> lider.Jugada
	4, // 2: lider.LiderManagement.Premio:input_type -> lider.VerMonto
	1, // 3: lider.LiderManagement.Unirse:output_type -> lider.Confirmacion
	3, // 4: lider.LiderManagement.Jugar:output_type -> lider.Estado
	5, // 5: lider.LiderManagement.Premio:output_type -> lider.Monto
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lider_proto_init() }
func file_proto_lider_proto_init() {
	if File_proto_lider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Peticion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Confirmacion); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Jugada); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerMonto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lider_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Monto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lider_proto_goTypes,
		DependencyIndexes: file_proto_lider_proto_depIdxs,
		MessageInfos:      file_proto_lider_proto_msgTypes,
	}.Build()
	File_proto_lider_proto = out.File
	file_proto_lider_proto_rawDesc = nil
	file_proto_lider_proto_goTypes = nil
	file_proto_lider_proto_depIdxs = nil
}
